name: build
on:
  [pull_request, push]
jobs:
  iac-scan:
    name: "Trigger IaC Scan" # modify to suit project name
    uses: Xttreme/cross-github-actions/.github/workflows/iac-scan.yaml@iac
    with:
      runs-on: ubuntu-latest
